### PR TITLE
fixtures for oauth app - created/updated not null

### PR DESCRIPTION
**Pull request by cezio**
oauth mode chanded  and requires created/updated fields in fixture now. Otherwise following exception happens on container init:

```
django4demo_master | 2018-06-11T15:40:33.660344396Z Traceback (most recent call last):
django4demo_master | 2018-06-11T15:40:33.660358230Z   File "/usr/local/bin/django-admin.py", line 5, in <module>
django4demo_master | 2018-06-11T15:40:33.660364200Z     management.execute_from_command_line()
django4demo_master | 2018-06-11T15:40:33.660369152Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
django4demo_master | 2018-06-11T15:40:33.660383543Z     utility.execute()
django4demo_master | 2018-06-11T15:40:33.660405659Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
django4demo_master | 2018-06-11T15:40:33.660436052Z     self.fetch_command(subcommand).run_from_argv(self.argv)
django4demo_master | 2018-06-11T15:40:33.660444170Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
django4demo_master | 2018-06-11T15:40:33.660489112Z     self.execute(*args, **cmd_options)
django4demo_master | 2018-06-11T15:40:33.660517175Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
django4demo_master | 2018-06-11T15:40:33.660543464Z     output = self.handle(*args, **options)
django4demo_master | 2018-06-11T15:40:33.660569537Z   File "/usr/local/lib/python2.7/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
django4demo_master | 2018-06-11T15:40:33.660577614Z     return super(Command, self).handle(*fixture_labels, **options)
django4demo_master | 2018-06-11T15:40:33.660582208Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
django4demo_master | 2018-06-11T15:40:33.660594156Z     self.loaddata(fixture_labels)
django4demo_master | 2018-06-11T15:40:33.660608224Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
django4demo_master | 2018-06-11T15:40:33.660622263Z     self.load_label(fixture_label)
django4demo_master | 2018-06-11T15:40:33.660627585Z   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
django4demo_master | 2018-06-11T15:40:33.660678146Z     obj.save(using=self.using)
django4demo_master | 2018-06-11T15:40:33.660685206Z   File "/usr/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 205, in save
django4demo_master | 2018-06-11T15:40:33.660712222Z     models.Model.save_base(self.object, using=using, raw=True, **kwargs)
django4demo_master | 2018-06-11T15:40:33.660735891Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
django4demo_master | 2018-06-11T15:40:33.660844066Z     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
django4demo_master | 2018-06-11T15:40:33.660850433Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
django4demo_master | 2018-06-11T15:40:33.660970474Z     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
django4demo_master | 2018-06-11T15:40:33.660981251Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
django4demo_master | 2018-06-11T15:40:33.661085486Z     using=using, raw=raw)
django4demo_master | 2018-06-11T15:40:33.661105864Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
django4demo_master | 2018-06-11T15:40:33.661114965Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
django4demo_master | 2018-06-11T15:40:33.661118730Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
django4demo_master | 2018-06-11T15:40:33.661242381Z     return query.get_compiler(using=using).execute_sql(return_id)
django4demo_master | 2018-06-11T15:40:33.661254136Z   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
django4demo_master | 2018-06-11T15:40:33.661500966Z     cursor.execute(sql, params)
django4demo_master | 2018-06-11T15:40:33.661508519Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
django4demo_master | 2018-06-11T15:40:33.661516690Z     return super(CursorDebugWrapper, self).execute(sql, params)
django4demo_master | 2018-06-11T15:40:33.661522467Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
django4demo_master | 2018-06-11T15:40:33.661529553Z     return self.cursor.execute(sql, params)
django4demo_master | 2018-06-11T15:40:33.661534718Z   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in _exit_
django4demo_master | 2018-06-11T15:40:33.661539715Z     six.reraise(dj_exc_type, dj_exc_value, traceback)
django4demo_master | 2018-06-11T15:40:33.661544195Z   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
django4demo_master | 2018-06-11T15:40:33.661548953Z     return self.cursor.execute(sql, params)
django4demo_master | 2018-06-11T15:40:33.661553525Z django.db.utils.IntegrityError: Problem installing fixture '/tmp/default_oauth_apps_docker.json': Could not load oauth2_provider.Application(pk=1001): null value in column "created" violates not-null constraint
django4demo_master | 2018-06-11T15:40:33.661557835Z DETAIL:  Failing row contains (1001, Jrchz2oPY3akmzndmgUTYrs9gczlgoV20YPSvqaV, http://188.165.216.96:None/geoserver/index.html
django4demo_master | 2018-06-11T15:40:33.661561175Z http://geonode:8..., confidential, authorization-code, rCnp5txobUo83EpQEblM8fVj3QT5zb5qRfxNsuPzCqZaiRyIoxM4jdgMiZKFfePB..., GeoServer, 1000, t, null, null, RS256).
```

### CODE REVIEW

**Comment by giohappy** [comment]
when was this change introduced in geonode?

**Comment by cezio** [comment]
I suspect this was caused by change of oauth2 dependency few days ago (see also tasks.py from that PR):

https://github.com/GeoNode/geonode/commit/117bbdccc38929216a4882999f586b3d51b4a0c4#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by giohappy** [comment]
if it's the case that patch should be merged asap @afabiani

**Comment by cezio** [comment]
This was introduced with https://github.com/GeoNode/geonode/pull/3825

Maybe we should ditch gn-project's based fixtures and use geonode's defaults (for this one of course, not in general).

**Pull request merged**
